from .fuze_error import FuzeError